# Generated by Django 3.1.3 on 2020-11-18 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20201118_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postlike',
            old_name='tameStamp',
            new_name='timeStamp',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='tameStamp',
            new_name='timeStamp',
        ),
    ]
